# Examples and Evaluation Metrics

We gradually develop any system we work on. For the classification task example, we:

1. Build baseline classifier
2. Build baseline evaluation
3. Do the optimization

The scope of this notebook is to explain and to show how to build the baseline evaluation and use it for further optimization.

In [5]:
import os

import dspy

In [2]:
lm = dspy.LM(
    "hosted_vllm/ibm-granite/granite-4.1-8b",
    api_base="http://boris:30000/v1",
)
dspy.settings.configure(lm=lm)

To set up a good evaluation process, we need two things: a good set of test data and a meaningful metric to evaluate how good each LM response is.

DSPy provides a small set of tools to help you streamline the evaluation process.

In [3]:
from datasets import load_dataset

In [4]:
ds = load_dataset("tuetschek/atis")
ds.set_format(type='pandas')
df_test = ds['test'][:]

ATIS_INTENT_MAPPING = {
   'abbreviation':                "Abbreviation and Fare Code Meaning Inquiry",
   'aircraft':                    "Aircraft Type Inquiry",
  #'aircraft+flight+flight_no':   "",
   'airfare':                     "Airfare and Fees Questions",
  #'airfare+flight_time':         "",
   'airline':                     "Airline Information Request",
  #'airline+flight_no':           "",
   'airport':                     "Airport Information and Queries",
   'capacity':                    "Aircraft Seating Capacity Inquiry",
   'Cheapest':                    "Cheapest Fare Inquiry",
   'city':                        "Airport Location Inquiry",
   'distance':                    "Airport Distance Inquiry",
   'flight':                      "Flight Booking Request",
  #'flight+airfare':              "",
   'flight_no':                   "Flight Number Inquiry",
   'flight_time':                 "Time Inquiry",
   'ground_fare':                 "Ground Transportation Cost Inquiry",
   'ground_service':              "Ground Transportation Inquiry",
  #'ground_service+ground_fare':  "Airport Ground Transportation and Cost Query",
   'meal':                        "Inquiry about In-flight Meals",
   'quantity':                    "Flight Quantity Inquiry",
   'restriction':                 "Flight Restriction Inquiry"
}
# Map the intents to their new names
df_test['intent'] = df_test['intent'].map(ATIS_INTENT_MAPPING)
df_test = df_test.dropna(subset=['intent'])
unique_intents = df_test['intent'].unique()

atis_train.csv:   0%|          | 0.00/850k [00:00<?, ?B/s]

atis_test.csv:   0%|          | 0.00/144k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/4978 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/893 [00:00<?, ? examples/s]

In [5]:
example_1 = dspy.Example(
    message = "I would like to find a flight from charlotte to las vegas that makes at "   
              "most one stop inbetween", 
    labels = unique_intents,
    intent_label = "Flight Booking Request").with_inputs("message", "labels")

We provide both: the inputs `message` and `labels`; and intended label. `with_inputs()` is used to indicate which fields are used in any calls to the LMs.

In [6]:
example_1

Example({'message': 'I would like to find a flight from charlotte to las vegas that makes at most one stop inbetween', 'labels': array(['Flight Booking Request', 'Airfare and Fees Questions',
       'Ground Transportation Inquiry', 'Inquiry about In-flight Meals',
       'Airport Information and Queries', 'Airline Information Request',
       'Time Inquiry', 'Airport Location Inquiry',
       'Ground Transportation Cost Inquiry', 'Flight Quantity Inquiry',
       'Abbreviation and Fare Code Meaning Inquiry',
       'Airport Distance Inquiry', 'Aircraft Type Inquiry',
       'Aircraft Seating Capacity Inquiry', 'Flight Number Inquiry'],
      dtype=object), 'intent_label': 'Flight Booking Request'}) (input_keys={'labels', 'message'})

In [7]:
# Create for all examples we have in "test" dataset
def create_examples_from_set(set_name, n=-1):
   ds = load_dataset("tuetschek/atis")
   ds.set_format(type='pandas')
   df = ds[set_name][:]
   df['intent'] = df['intent'].map(ATIS_INTENT_MAPPING)
   df = df.dropna(subset='intent')
   unique_intents = df['intent'].unique()
   if n > 0:
      df = df.sample(n=n, random_state=42)
 
   examples = []
   for index in df.index:
       row = df.loc[index]
       examples.append(
           dspy.Example(message=row['text'],
                        labels=unique_intents.tolist(),
               intent_label=row['intent']).with_inputs('message', 'labels')
       )
   return examples
 
test_set = create_examples_from_set('test')

DSPy tends to assume train-validation-test splits.  
For LM-based applications, we might use splits like 15-70-15 or 20-30-50, which means only a small fraction of the data is used for training. With DSPy, it’s not always necessary to explicitly separate the training and validation data. Most optimizers accept just a training set and, if no validation set is provided, will **automatically split it into training and validation sets**. In general, DSPy recommends using about 30 to 300 examples for both training and validation.

In [8]:
import numpy as np

In [9]:
# We split "train" into train and validation sets
train_val_set = create_examples_from_set('train', n=200)

np.random.shuffle(train_val_set)
train_set = train_val_set[:20]
val_set = train_val_set[20:]

In [10]:
# We split "test" into dev and test sets
dev_test_set = create_examples_from_set('test', n=100)

np.random.shuffle(dev_test_set )
dev_set = dev_test_set [:50]
test_set = dev_test_set[50:]
# Yeah, it is confusing.

DSPy specifies a simple format to define your metric function. Metric functions must take three parameters: example, LM response, trace.

In [11]:
def validate_answer(example: dspy.Example, prediction: dspy.Prediction, trace=None):
   return example.intent_label == prediction.intent_label

In [12]:
# Since "validate_answer" is regular Python function, we can always test in unit tests or directly in the code
booking_flight_example = dspy.Example(
    message="I want to book a flight", 
    labels=unique_intents, 
    intent_label='Flight Booking Request').with_inputs("message", "labels")
 
booking_flight_prediction = dspy.Prediction(intent_label='Flight Booking Request')
 
print(validate_answer(booking_flight_example, booking_flight_prediction))

True

In [13]:
# We should also test with at least one negative example.
booking_flight_example = dspy.Example(
    message="I want to book a flight",
    labels=unique_intents,
    intent_label='Flight Booking Request').with_inputs("message", "labels")
 
booking_flight_prediction = dspy.Prediction(intent_label='Airport Distance Inquiry')
 
print(validate_answer(booking_flight_example, booking_flight_prediction))

False

# Evaluating the Baseline Model

DSPy program is `LM + Signature + Module + Optimization`  
However, the baseline program is only `LM + Signature + Module`

In [14]:
import time

In [15]:
len(dev_set)

50

In [16]:
class IntentSignature(dspy.Signature):
   """
   Classify the message into one or more of the possible intent labels.
   """
   message: str      = dspy.InputField()
   labels: list[str] = dspy.InputField()
   intent_label: str = dspy.OutputField(desc="Return the closest matches if any are "
      "reasonably close. Otherwise return None")

In [17]:
def evaluate_baseline(model="hosted_vllm/ibm-granite/granite-4.1-8b", num_threads=1):
    lm = dspy.LM(
        model=model,
        api_base="http://boris:30000/v1",
        cache=False
    )
    dspy.settings.configure(lm=lm)
    
    classifier = dspy.Predict(IntentSignature)
    evaluator = dspy.Evaluate(devset=dev_set,
                             num_threads=num_threads, 
                             display_progress=True, 
                             display_table=5, 
                             provide_traceback=True,
                             max_errors=5)
    
    start_time = time.time()
    results = evaluator(classifier, metric=validate_answer)
    end_time = time.time()
    
    print(f"total time: {end_time - start_time}")
    return results

In [18]:
eval_results = evaluate_baseline()

Average Metric: 42.00 / 50 (84.0%): 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:23<00:00,  2.11it/s]

2026/08/25 20:04:00 INFO dspy.evaluate.evaluate: Average Metric: 42 / 50 (84.0%)

,message,labels,example_intent_label,pred_intent_label,validate_answer
0,find flight from memphis to cincinnati on sunday,"['Flight Booking Request', 'Airfare and Fees Questions', 'Ground T...",Flight Booking Request,Flight Booking Request,✔️ [True]
1,list the alaska airlines flights a departing from burbank,"['Flight Booking Request', 'Airfare and Fees Questions', 'Ground T...",Flight Booking Request,Flight Booking Request,✔️ [True]
2,i need a flight from phoenix to atlanta,"['Flight Booking Request', 'Airfare and Fees Questions', 'Ground T...",Flight Booking Request,Flight Booking Request,✔️ [True]
3,get saturday fares from washington to toronto,"['Flight Booking Request', 'Airfare and Fees Questions', 'Ground T...",Airfare and Fees Questions,Airfare and Fees Questions,✔️ [True]
4,st. louis to st. paul thursday after 10 am,"['Flight Booking Request', 'Airfare and Fees Questions', 'Ground T...",Flight Booking Request,Flight Booking Request,✔️ [True]

total time: 23.657360076904297

In [19]:
eval_results.score

84.0

In [20]:
eval_results.results[:2]

[(Example({'message': 'find flight from memphis to cincinnati on sunday', 'labels': ['Flight Booking Request', 'Airfare and Fees Questions', 'Ground Transportation Inquiry', 'Inquiry about In-flight Meals', 'Airport Information and Queries', 'Airline Information Request', 'Time Inquiry', 'Airport Location Inquiry', 'Ground Transportation Cost Inquiry', 'Flight Quantity Inquiry', 'Abbreviation and Fare Code Meaning Inquiry', 'Airport Distance Inquiry', 'Aircraft Type Inquiry', 'Aircraft Seating Capacity Inquiry', 'Flight Number Inquiry'], 'intent_label': 'Flight Booking Request'}) (input_keys={'labels', 'message'}),
  Prediction(
      intent_label='Flight Booking Request'
  ),
  True),
 (Example({'message': 'list the alaska airlines flights a departing from burbank', 'labels': ['Flight Booking Request', 'Airfare and Fees Questions', 'Ground Transportation Inquiry', 'Inquiry about In-flight Meals', 'Airport Information and Queries', 'Airline Information Request', 'Time Inquiry', 'Airport Location Inquiry', 'Ground Transportation Cost Inquiry', 'Flight Quantity Inquiry', 'Abbreviation and Fare Code Meaning Inquiry', 'Airport Distance Inquiry', 'Aircraft Type Inquiry', 'Aircraft Seating Capacity Inquiry', 'Flight Number Inquiry'], 'intent_label': 'Flight Booking Request'}) (input_keys={'labels', 'message'}),
  Prediction(
      intent_label='Flight Booking Request'
  ),
  True)]

Overall score of the model is a good start. But with classification problems, it’s also useful to look at the model’s accuracy on each class.  
We often want to check for consistency. But it usually requires to go even beyond and re-run the same dataset multiple time and confirm that the scores do not deviate too much.

In [21]:
from sklearn.metrics import classification_report

In [22]:
predictions = []
groundtruths = []
for triplet in eval_results.results:
    example, prediction, score = triplet
    groundtruths.append(example.intent_label)
    predictions.append(prediction.intent_label.strip("'"))

In [23]:
print(classification_report(groundtruths, predictions))

                                                        precision    recall  f1-score   support

                              "Flight Booking Request"       0.00      0.00      0.00         0
"Flight Booking Request", "Airfare and Fees Questions"       0.00      0.00      0.00         0
            Abbreviation and Fare Code Meaning Inquiry       1.00      1.00      1.00         3
                                 Aircraft Type Inquiry       0.00      0.00      0.00         0
                            Airfare and Fees Questions       1.00      0.33      0.50         3
                           Airline Information Request       1.00      1.00      1.00         2
                       Airport Information and Queries       0.00      0.00      0.00         0
                                Flight Booking Request       0.97      0.85      0.91        40
    Flight Booking Request, Airfare and Fees Questions       0.00      0.00      0.00         0
                  Flight Booking Request, Time Inquiry       0.00      0.00      0.00         0
                                 Flight Number Inquiry       1.00      1.00      1.00         1
                         Ground Transportation Inquiry       1.00      1.00      1.00         1
                                          Time Inquiry       0.00      0.00      0.00         0

                                              accuracy                           0.84        50
                                             macro avg       0.46      0.40      0.42        50
                                          weighted avg       0.98      0.84      0.90        50

/home/dima/Projects/ai/.venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/dima/Projects/ai/.venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/dima/Projects/ai/.venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [24]:
from sklearn.metrics import f1_score

In [25]:
f1_score(groundtruths, predictions, average='macro')

0.4158974358974359

Defining a metric function is typically the most difficult part of working with DSPy.

# Effective Metric Functions

To evaluate or optimize any DSPy programs we create, we must have metric function that can reliably evaluate the output they produce. Classification problem or structured output are easy. Other use cases are not: summarization, style-transfer, translation, open-ended question answering, etc.

__Defining the metric functions is often the most difficult step when working with LMs.__

For this example, we are going to use summarization. 

In general, it is difficult to determine how good a document summary is. Nevertheless, summaries can be evaluated in a meaningful way.  
Let's consider data **with label** first. We expect LM's summaries to be at least slightly different from the ground truth. We have three tools available for us:

- Lexical comparison: basic words counting
- Create and compare text embeddings representing both summaries (cosine similarity, dot product, and Euclidean distance)
- LLM as a Judge (can work without ground truth)

In [66]:
from datasets import load_dataset
import pandas as pd
import copy

In [48]:
ds = load_dataset("knkarthick/dialogsum")
ds.set_format(type='pandas')

In [49]:
df_train = ds['train'][:]
df_test = ds['test'][:]

In [50]:
df_train.head()

,id,dialogue,summary,topic
0,train_0,"#Person1#: Hi, Mr. Smith. I'm Doctor Hawkins. ...","Mr. Smith's getting a check-up, and Doctor Haw...",get a check-up
1,train_1,"#Person1#: Hello Mrs. Parker, how have you bee...",Mrs Parker takes Ricky for his vaccines. Dr. P...,vaccines
2,train_2,"#Person1#: Excuse me, did you see a set of key...",#Person1#'s looking for a set of keys and asks...,find keys
3,train_3,#Person1#: Why didn't you tell me you had a gi...,#Person1#'s angry because #Person2# didn't tel...,have a girlfriend
4,train_4,"#Person1#: Watsup, ladies! Y'll looking'fine t...",Malik invites Nikki to dance. Nikki agrees if ...,dance

In [51]:
def create_examples(df):
    examples = []
    for i in range(len(df)):
        example = dspy.Example({
            'dialog':df.iloc[i]['dialogue'],
            'summary':df.iloc[i]['summary'],
            'true_score': 1.0 
        }).with_inputs('dialog', 'summary')
        examples.append(example)
    return examples

In [52]:
test_examples = create_examples(df_test)
train_examples = create_examples(df_train)

In [53]:
summarizer_train_data = train_examples[:50]
summarizer_val_data   = train_examples[50:150]
summarizer_test_data  = test_examples[:500]

In [67]:
neg_examples = copy.deepcopy(judge_val_data)
for i in range(99):
    neg_examples[i]['summary'] = neg_examples[i+1]['summary']
    neg_examples[i]['true_score'] = 0.0
judge_val_data = judge_val_data + neg_examples

Let's establish a baseline

In [68]:
lm = dspy.LM(
    "openrouter/openai/gpt-5.6-luna",
    api_base="https://openrouter.ai/api/v1",
    api_key=os.getenv("OPENROUTER_API_KEY"),
    cache=False
)
dspy.settings.configure(lm=lm)

In [69]:
lm("Hello, how are you doing?")

['Hello! I’m doing well, thanks for asking. How are you?']

In [70]:
class SummarySignature(dspy.Signature):
    """Summarize a conversation between two people."""
    dialog: str = dspy.InputField()
    summary: str = dspy.OutputField()

In [71]:
prog_summarizer = dspy.Predict(SummarySignature)

In [72]:
print(train_examples[0]['summary'])
pred = prog_summarizer(dialog=summarizer_train_data[0]['dialog'])
print(pred)

Mr. Smith's getting a check-up, and Doctor Hawkins advises him to have one every year. Hawkins'll give some information about their classes and medications to help Mr. Smith quit smoking.
Prediction(
    summary='Mr. Smith visits Dr. Hawkins for a check-up after not seeing a doctor for five years. Dr. Hawkins explains the importance of annual check-ups for early detection of serious illnesses. His eyes and ears appear normal, but he admits to smoking. The doctor warns that smoking can cause lung cancer and heart disease and recommends quitting. Mr. Smith says he has tried many times, so the doctor offers information about cessation classes and medications.'
)

## Evaluating Using Embeddings

In [16]:
from sklearn.metrics.pairwise import cosine_similarity
from sentence_transformers import SentenceTransformer

Task was destroyed but it is pending!
task: <Task pending name='Task-262' coro=<_async_in_context.<locals>.run_in_context_pre311() done, defined at /Users/dima/Projects/ai/.venv/lib/python3.10/site-packages/ipykernel/utils.py:76> wait_for=<Task pending name='Task-263' coro=<_async_in_context.<locals>.preserve_context() running at /Users/dima/Projects/ai/.venv/lib/python3.10/site-packages/ipykernel/utils.py:68> cb=[Task.task_wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/dima/Projects/ai/.venv/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py:563]>
/Users/dima/Projects/ai/.venv/lib/python3.10/site-packages/joblib/externals/loky/_base.py:22: RuntimeWarning: coroutine '_async_in_context.<locals>.preserve_context' was never awaited
  class Future(_BaseFuture):
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Task was destroyed but it is pending!
task: <Task pending name='Task-263' coro=<_async_in_context.<locals>.preserve_context() running at /Users/dima/Projects/ai/.venv/lib/python3.10/site-packages/ipykernel/utils.py:68> cb=[Task.task_wakeup()]>

In [19]:
encoder_func = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2", token=False).encode

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [20]:
def embedding_score(example, prediction, trace=None):
    v1 = encoder_func(example.summary)
    v2 = encoder_func(prediction.summary)
    return cosine_similarity([v1], [v2])[0][0]

In [21]:
embedding_score(summarizer_train_data[0], pred)

np.float32(0.76788723)

## Evaluating Using LLM as a Judge

In [73]:
# SemanticF1 is a bit limited in that it requires the Examples to contain fields called question and response,
# though the general ideas are useful and easy to adapt, for example, by taking the DSPy code and modifying it slightly to use the field names in your examples.
from dspy.evaluate import SemanticF1

In [74]:
test_example = dspy.Example( 
   question="What is the Rime of the Ancient Mariner about?", 
   response="A sailor stops a wedding guest to recount his cursed journey after he "
            "thoughtlessly shoots an albatross, a bird of good omen, bringing death to " 
            "shipmates and himself.")
 
test_pred = dspy.Prediction(response=
   "A mariner recalls his voyage at sea, which was doomed after he killed a bird")
 
semantic_f1 = SemanticF1()
semantic_f1(test_example, test_pred)

Prediction(
    score=0.6666666666666666
)

A different approach is to implement a an LLM as a Judge ourselves.

In [75]:
def evaluate_summary(example: dspy.Example, prediction: dspy.Prediction, trace=None):
    judge = dspy.Predict("ground_truth_summary, system_summary -> summary_quality: float")
    return judge(
        ground_truth_summary=example.summary,
        system_summary=prediction.summary)

In [76]:
evaluate_summary(summarizer_train_data[0], pred)

Prediction(
    summary_quality=0.95
)

Given that the judges are DSPy programs themselves, they can be evaluated and optimized like other DPSy programs, allowing us to ensure that these judges are fairly evaluating or optimizing these programs. Also, for completeness and groundedness DSPy has some pre-defined signatures: https://github.com/stanfordnlp/dspy/blob/main/dspy/evaluate/auto_evaluation.py

Whenever we are going to use LLM as a Judge, we start from defining it as a Signature. It can have any meaningful criteria.

In [77]:
class QASingature(dspy.Signature):
    '''Your task is to judge the summary of a dialog'''
 
    dialog: str = dspy.InputField()
    summary: str = dspy.InputField()
    
    salient: float = dspy.OutputField(desc="On a scale from 0.0 to 1.0")
    named_entities: float = dspy.OutputField(desc="On a scale from 0.0 to 1.0")

In [78]:
def get_final_score(prediction: dspy.Prediction):
    return ((prediction.salient + prediction.named_entities) / 2) > 0.5

In [79]:
qa_judge = dspy.ChainOfThought(QASingature)  # Judge Signature

Now that we have a judge program, we can evaluate it!

In [80]:
from dspy import Evaluate 
 
def qa_judge_metric(example: dspy.Example, prediction: dspy.Prediction, trace=None):
    predicted_score = get_final_score(prediction)
    return example.true_score == predicted_score

In [81]:
evaluate = Evaluate(devset=judge_val_data, num_threads=1, display_table=5,
                    display_progress=True, max_errors=3, provide_traceback=True)

In [ ]:
evaluate(qa_judge, metric=qa_judge_metric)

Whenever we are not happy with the Judge program, we can use `SIMBA`, `GEPA`, etc. optimizers to make it better. 

After that, we can switch to a real metric function with an optimized judge:

In [84]:
def qa_metric(example: dspy.Example, prediction: dspy.Prediction, trace=None):
    judge_pred = simba_qa_judge(dialog=example['dialog'], summary=prediction['summary'])
    return get_final_score(judge_pred)